name: Build ARM
on: [push, pull_request]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   cibw_archs: "native"
          - os: ubuntu-latest
            cibw_archs: "aarch64"
          # - os: windows-latest
          #   cibw_archs: "native ARM64"
          # - os: macos-latest
          #   cibw_archs: "native arm64"

    steps:
      - name: Set up QEMU
        if: matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_SKIP: "pp*"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
