name: Upload Python Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        exclude:
          # excludes py27 on Windows
          - os: windows-latest
            python-version: 2.7

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - uses: RalfG/python-wheels-manylinux-build@v0.3.3
    - name: Build manylinux wheel
      if: startsWith(matrix.os, 'ubuntu-latest')
      with:
        python-versions: 'cp27-cp27m cp36-cp36m cp37-cp37m cp38-cp38m cp39-cp39m'
    - name: Build for rest and publish
      env:
        TWINE_USERNAME: ${{ secrets.TPYPI_USERNAME }}
        TW1INE_PASSWORD: ${{ secrets.TPYPI_PASSWORD }}
      if: "!(startsWith(matrix.os, 'ubuntu-latest')"
      run: |
        git submodule update --init --recursive
        python setup.py sdist bdist_wheel build --enable-dex
        # twine upload --repository testpypi dist/*
